#define BITS_PER_CHAR 8
#define sizeof_char 1
#define char_width 8
#define sizeof_short 2
#define short_width 16
#define sizeof_int 4
#define int_width 32
#define sizeof_long 8
#define long_width 64
#define sizeof_long_long 8
#define long_long_width 64
#define sizeof_float 4
#define float_width 32
#define sizeof_double 8
#define double_width 64
